# Generated by Django 4.2.3 on 2023-12-21 18:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('delivery', models.CharField(choices=[('minsk', 'Доставка курьером по Минску'), ('rb', 'Доставка Европочтой по РБ'), ('cdek', 'СДЭК, города РФ')], default='minsk', max_length=100, verbose_name='Доставка')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paymentMethod', models.CharField(choices=[('card', 'Банковской картой'), ('cash          ', 'Оплата при получении')], default='card', max_length=100, verbose_name='Способ оплаты')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплаченный')),
                ('executed', models.BooleanField(default=False, verbose_name='Выполненный')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='clothes.product')),
            ],
        ),
    ]
