# Generated by Django 4.2.3 on 2023-10-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_information_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ('id',), 'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
    ]
