# Generated by Django 4.2.3 on 2023-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_information_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=5, verbose_name='Размеры')),
                ('russianSize', models.TextField(blank=True, verbose_name='Российский размер')),
                ('chest', models.IntegerField(blank=True, verbose_name='Обхват груди')),
                ('waist', models.IntegerField(blank=True, verbose_name='Обхват талии')),
                ('hip', models.IntegerField(blank=True, verbose_name='Обхват бедер')),
            ],
        ),
    ]
